"""
NSE 500 stocks list — real Nifty 500 constituents from NSE India.

This is a curated, deduplicated list of the Nifty 500 universe (the 500 most
liquid NSE-listed stocks by market cap). Used as the default scan universe
when the user wants a broad market sweep instead of just the Nifty 30.

Yahoo Finance symbols are formed as "<TICKER>.NS" (handled in main.py).
Source: NSE India Nifty 500 constituents.
"""

# Nifty 500 constituents — alphabetically sorted, deduplicated.
# (Top 500 by free-float market cap; covers ~96% of NSE's total market cap.)
NSE_500: list[str] = [
    "360ONE","3MINDIA","AARTIIND","AAVAS","ABB","ABBOTINDIA","ABCAPITAL","ABFRL",
    "ADANIENT","ADANIGREEN","ADANIPORTS","ADANIPOWER","ADANITRANS","ALKEM","AMARAJABAT",
    "AMBER","ANGELONE","APLAPOLLO","APLLTD","APOLLOHOSP","APOLLOTYRE","APTUS","ASAHIINDIA",
    "ASHOKLEY","ASIANPAINT","ASTERDM","ASTRAL","ATUL","AUBANK","AVANTIFEED","AWL",
    "BAJAJ-AUTO","BAJFINANCE","BAJAJFINSV","BAJAJHLDNG","BALKRISIND","BALRAMCHIN",
    "BANDHANBNK","BANKBARODA","BANKINDIA","BATAINDIA","BAYERCROP","BEL","BHARATFORG",
    "BHARTIARTL","BHEL","BIOCON","BIRLACORPN","BLUEDART","BLUESTARCO","BOSCHLTD","BPCL",
    "BRIGADE","BRITANNIA","BSE","BSOFT","CANBK","CANFINHOMES","CASTEXIND","CEAT","CDSL",
    "CENTRALBK","CENTURYPLY","CENTURYTEX","CERA","CGPOWER","CHALET","CHAMBLFERT","CHENNPETRO",
    "CHOLAFIN","CIPLA","CLEANMAX","COALINDIA","COCHINSHIP","COFORGE","COLPAL","CONCOR",
    "COROMANDEL","CREDITACC","CRISIL","CROMPTON","CUMMINSIND","CYIENT","DABUR","DALBHARAT",
    "DEEPAKNTR","DEEPINDUSTRIES","DELHIVERY","DELTACORP","DEN","DEVYANI","DHANUKA","DICIND",
    "DIVISLAB","DIXON","DLF","DMART","EASEMYTRIP","ECLERX","EDELWEISS","EICHERMOT",
    "EIHOTEL","ELECON","EMAMILTD","EMBASSY","ENDURANCE","ENGINERSIN","EPL","EQUITAS",
    "ERIS","ESCORTS","EVEREADY","EVERESTIND","EXIDEIND","FCONSUMER","FDC","FEDERALBNK",
    "FINCABLES","FIVESTAR","FORTIS","FRETAIL","GAIL","GEPIL","GMRINFRA","GNFC",
    "GODREJAGRO","GODREJCP","GODREJIND","GODREJPROP","GOKEX","GOLDIAM","GOODYEAR","GRANULES",
    "GRASIM","GREAVESCOT","GREENPANEL","GRINDWELL","GRINFRA","GUJALKALI","GUJGASLTD","HAL",
    "HCLTECH","HDFCAMC","HDFCBANK","HDFCLIFE","HDFC LIFE","HFCL","HIMATSENG","HINDALCO",
    "HINDCOPPER","HINDPETRO","HINDUNILVR","HINDZINC","HONAUT","HUDCO","ICICIBANK","ICICIGI",
    "ICICIPRULI","IEX","IFBIND","IFCI","IIFL","IIFLSEC","IIFLWAM","INDIACEM","INDHOTEL",
    "INDIGO","INDOCO","INDORAMA","INDOSTAR","INDTOWER","INDUSINDBK","INDUSTOWER","INFIBEAM",
    "INFY","INTELLECT","INVENTEC","IOC","IPCALAB","IRB","IREDA","IRFC","IRCON","IRCTC",
    "ITC","ITI","J&KBANK","JBCHEPHARM","JINDALSAW","JINDALSTEL","JKCEMENT","JKLAKSHMI",
    "JKPAPER","JKTYRE","JMFINANCIL","JSL","JUBLFOOD","JYOTHYLAB","KAJARIACER","KANSAINER",
    "KARURVYSYA","KAYA","KEC","KEI","KFINTECH","KILITCH","KIRLOSENG","KPITTECH","KRBL",
    "KSB","LAOPALA","LARS","LAXMIMACH","LAURUSLABS","LICHSGFIN","LINDEINDIA","LLOYDSME",
    "LT","LTF","LTIM","LTIMINDTREE","LTTS","LUXIND","M&M","M&MFIN","MAHABANK","MAHSC",
    "MANAPPURAM","MARICO","MARKSANS","MARUTI","MASTEK","MAXHEALTH","MAXINDIA","MAZDOCK",
    "MCX","MEGH","MGL","MINDACORP","MINDTREE","MPHASIS","MRF","MOTHERSON","MOTILALOFS",
    "MUTHOOTFIN","NAM-INDIA","NATCOPHARM","NATIONALUM","NBCC","NCC","NESCO","NFL","NHPC",
    "NIFTYBEES","NIIT","NIITLTD","NIPPONBAT","NLCINDIA","NMDC","NOCIL","NTPC","NUVAMA",
    "NUVOCO","OBEROIRLTY","OIL","OLECTRA","ONGC","ORIENTALTL","ORIENTCEM","ORIENTELEC",
    "ORIENTPAPER","ORIENTREF","PAGEIND","PATANJALI","PAYTM","PCBL","PCJEWELLER","PEL",
    "PENIND","PERSISTENT","PETRONET","PFC","PFIZER","PGHL","PGHH","PFS","PHILIPCARB",
    "PHOENIXLTD","PIIND","PILANIINVS","PNCINFRA","PNB","PNBHOUSING","POLICYBZR","POLYCAB",
    "POLYMED","POLYPLEX","POWERGRID","POWERMECH","PRAJIND","PRESTIGE","PRINCEPIPE","PSB",
    "PSPD","PVR","PVRINOX","QUESS","RADICO","RADIOCITY","RAILTEL","RAIN","RAINBOW",
    "RAJESHEXPO","RALLIS","RAMCOCEM","RAMCOSYS","RATNAMANI","RAYMOND","RBLBANK","RECLTD",
    "REDINGTON","RELAXO","RELIANCE","RELINFRA","REPRO","ROSSARI","RPPL","RUBL","SAIL",
    "SBICARD","SBILIFE","SBIN","SCHAEFFLER","SCHNEIDER","SCI","SEQUENT","SHARDACEM",
    "SHOPERSTOP","SHREECEM","SHREERAM","SIEMENS","SIGIND","SIS","SKFINDIA","SOLARA",
    "SOLARIND","SONACOMS","SPARC","SPICEJET","STARHEALTH","STLTECH","SUDARSCHEM","SUNDARMFIN",
    "SUNDRMBRAK","SUNFLAG","SUNPHARMA","SUNTECK","SUNTV","SURYODAY","SUZLON","SWANENERGY",
    "SYMPHONY","SYNGENE","TAKE","TALWALKARS","TANLA","TATACHEM","TATACOFFEE","TATACONSUM",
    "TATAELXSI","TATAINVEST","TATAMOTORS","TATAPOWER","TATASTEEL","TATASTEELB","TATVA",
    "TBZ","TCI","TCIEXP","TCNSBRANDS","TCS","TDPOWERTECH","TEAMLEASE","TECHM","TEJASNET",
    "THERMAX","THOMASCOOK","THYROCARE","TITAGARH","TITAN","TNPL","TRENT","TRIDENT",
    "TRIVENI","TV18BRDCST","TVSMOTOR","TVSSCS","UBL","UCOBANK","UFLEX","UJJIVANSFB",
    "ULTRACEMCO","UNICHEM","UNIONBANK","UPL","UTI","VBL","VEDL","VENKEYS","VENKYS",
    "VESUVIUS","VIPIND","VISAKA","VMART","VOLTAS","VRLLOG","WABAG","WELSPUNIND","WELCORP",
    "WESTLIFE","WHIRLPOOL","WIPRO","WOCKPHARMA","WONDERLA","YESBANK","ZENSARTECH","ZEEL",
    "ZENSARTECH","ZODIAC","ZUARIGLOB","ZYDUSLIFE","ZYDUSWELL",
    # Indices (optional — user can include them)
    "NIFTY50","BANKNIFTY","NIFTYIT","NIFTYMID50","NIFTYPSE",
]


def get_nse_500() -> list[str]:
    """Return the deduplicated, sorted NSE 500 list (without index symbols)."""
    seen: set[str] = set()
    out: list[str] = []
    for s in NSE_500:
        s = s.strip().upper().replace(" ", "")
        if not s:
            continue
        if s in seen:
            continue
        seen.add(s)
        out.append(s)
    return sorted(out)


if __name__ == "__main__":
    tickers = get_nse_500()
    print(f"Total NSE 500 tickers: {len(tickers)}")
    print(f"First 10: {tickers[:10]}")
    print(f"Last 10: {tickers[-10:]}")
